format = """
[](#9A348E)\
$os\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#86BBD8 bg:#06969A)\
$battery\
[](fg:#06969A bg:#33658A)\
$status$cmd_duration$time\
[ ](fg:#33658A)\
"""

[battery]
format = '[$symbol$percentage ]($style)'

[[battery.display]]
threshold = 10
style = 'bold fg:#ffffff bg:#06969A'

[[battery.display]]
threshold = 95
style = 'fg:#ffffff bg:#06969A'

[cmd_duration]
format = '[  $duration]($style)'
style = 'bold fg:#ffffff bg:#33658A'
show_milliseconds = true
show_notifications = true
min_time_to_notify = 10_000

[directory]
style = "bold bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""
"Sites" = "󰖟"
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[git_branch]
symbol = ""
style = "fg:#ffffff bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#ffffff bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = ""
style = "fg:#ffffff bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#ffffff bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[status]
format = '[ $symbol $status]($style)'
style = "bold fg:#ffffff bg:#33658A"
disabled = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#ffffff bg:#33658A"
format = '[ ♥ $time ]($style)'

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:#ffffff bg:#9A348E"
style_root = "fg:#ffffff bg:#9A348E"
format = '[󱐋]($style)'
disabled = false



#########################
### Disabled packages ###
########################€

[azure]
disabled = true

[buf]
disabled = true

[bun]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[direnv]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[fennel]
disabled = true

[fill]
disabled = true

[fossil_branch]
disabled = true

[fossil_metrics]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[guix_shell]
disabled = true

[gradle]
disabled = true

[haskell]
disabled = true

[haxe]
disabled = true

[helm]
disabled = true

[hg_branch]
disabled = true


[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[lua]
disabled = true

[meson]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[ocaml]
disabled = true

[opa]
disabled = true

[openstack]
disabled = true

[os]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[pijul_channel]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[quarto]
disabled = true

[rlang]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[scala]
disabled = true

[solidity]
disabled = true

[spack]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[typst]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true
